version: '3.5'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  redis:
    container_name: redis_cache
    image: redis:7.0-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis:/data

networks:
  postgres:
    driver: bridge

volumes:
    postgres:
    redis: